Controllers/DeckbuildersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace L5R_DBH_MVC.Controllers
{
    public class DeckbuildersController : Controller
    {
        // GET: Deckbuilders
        public ActionResult Index()
        {
            return View();
        }
    }
}

Views/Shared/_Footer.cshtml
 
<div class="footer-text">
    <p>&copy; @DateTime.Now.Year - L5R:DBH</p>
    <p>The source material, text and images, presented on this site, is copyrighted by Fantasy Flight Games.</p>
    <p>Legend of the Five Rings is a trademark of Fantasy Flight Games.</p>

    <p>This website is not produced, endorsed, supported, or affiliated with Fantasy Flight Games.</p>
</div>

Views/Shared/_L5R_Cards.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - L5R:DBH</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/cards")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @Html.Partial("_Footer")
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/cards")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_L5R_Decks.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - L5R:DBH</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/decks")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @Html.Partial("_Footer")
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/decks")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_L5R_SidePages.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - L5R:DBH</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/sidepages")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @Html.Partial("_Footer")
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - L5R:DBH</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @Html.Partial("_Footer")
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("L5R:DBH", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Cards","Index","Cards")</li><!--name,view,folder-->
                <li>@Html.ActionLink("Deckbuilder","Index","Deckbuilders")</li>
                <li>@Html.ActionLink("Decks","Index","Decks")</li>
                <li>@Html.ActionLink("About","About","Home")</li>
                <li>@Html.ActionLink("Contact","Contact","Home")</li>

            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>

Views/Shared/_l5r-cards.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - L5R:DBH</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/cards")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - L5R:DBH</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_l5r_Deckbuilder.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - L5R:DBH</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/deckbuilder")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @Html.Partial("_Footer")
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/deckbuilder")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_l5r_content.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - L5R:DBH</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/l5r")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - L5R:DBH</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>